FERIDriveApp/WebAppFeriDrive/Models/Prevoz.cs
using System;
using WebAppFeriDrive.Models;
public class Prevoz {

	private int cena;
	private Kraj krajOd;
	private Kraj krajDo;
	private DateTime datum;
    private Uporabnik uporabnik;

    private RezultatIskanja[] rezultatIskanjas;

    public Prevoz(int cena, Kraj krajOd, Kraj krajDo, DateTime datum, Uporabnik uporabnik)
    {
        this.Cena = cena;
        this.KrajOd = krajOd;
        this.KrajDo = krajDo;
        this.Datum = datum;     
        this.uporabnik = uporabnik;
        

    }
   
 
    public int Cena { get => cena; set => cena = value; }
    public Kraj KrajOd { get => krajOd; set => krajOd = value; }
    public Kraj KrajDo { get => krajDo; set => krajDo = value; }
    public DateTime Datum { get => datum; set => datum = value; }
    public Uporabnik Uporabnik { get => uporabnik; set => uporabnik = value; }


    public void Samoodstranitev() {
		throw new System.Exception("Not implemented");
	}

	

}

FERIDriveApp/WebAppFeriDrive/Controllers/PrevozController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppFeriDrive.Models;

namespace WebAppFeriDrive.Controllers
{
    public class PrevozController : Controller
    {
        private static string path = System.Web.Hosting.HostingEnvironment.MapPath(@"~/App_Data/FERIDRIVE.mdf");

        private static string connectionString = " Data Source =.\\SQLEXPRESS;" +
            "AttachDbFilename = " + path + "; " +
            "Integrated Security = True;" +
            "Connect Timeout = 30;" +
            "User Instance = True";
        public ActionResult AddPrevoz() => View();
        private static List<UporabnikovPrevoz> prevozi = new List<UporabnikovPrevoz>();
        [HttpGet]
        public ActionResult DodajanjePrevoza(string model, string cena, string krajPrihoda, string krajOdhoda, string datum, string ura)
        {
            string dtStr = datum + " " + ura;
            DateTime dt = DateTime.ParseExact(dtStr, "yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture);
            int c = Int32.Parse(cena);
            Kraj kraj1 = new Kraj(krajPrihoda, 0);
            int idKrajPrihoda = kraj1.insertKraj();
            Kraj kraj2 = new Kraj(krajOdhoda, 0);
            int idKrajOdhoda = kraj2.insertKraj();

            UporabnikovPrevoz novPrevoz = new UporabnikovPrevoz(model, c, kraj1, kraj2, dt, new Uporabnik());
            prevozi.Add(novPrevoz);
            int idUporabnika = Int32.Parse(Session["id"].ToString());
            novPrevoz.insertPrevoz(idKrajOdhoda, idKrajPrihoda, idUporabnika);

            DateTime date = DateTime.Now;
            return View("Prevozi",Povprasevanja.vrniVsePrevoze(-1,date));
        }

        public ActionResult iskanjePrevoza(string krajOdhoda, string krajPrihoda, string datum, string ura)
        {
            if (krajOdhoda != null && krajPrihoda != null && datum != "" && ura != "")
            {
                List<UporabnikovPrevoz> p1 = Povprasevanja.vrniIskanePrevoze(krajOdhoda, krajPrihoda, datum, ura,DateTime.Now);
                return View("Prevozi", p1);

            }
            else if (krajOdhoda != null && krajPrihoda != null && datum == "" && ura == "")
            {
                List<UporabnikovPrevoz> p2 = Povprasevanja.vrniIskanePrevoze2(krajOdhoda, krajPrihoda,DateTime.Now);
                return View("Prevozi", p2);
            }
            else if (krajOdhoda == "" && krajPrihoda == "" && datum != "")
            {
                List<UporabnikovPrevoz> p3 = Povprasevanja.vrniIskanePrevoze3(datum, "00:00",DateTime.Now);
                return View("Prevozi", p3);
            }
            return View("Prevozi");


        }

        public ActionResult Prevozi()
        {

            List<UporabnikovPrevoz> p = Povprasevanja.vrniVsePrevoze(-1,DateTime.Now);

            return View(p);
        }

        public ActionResult Details(int id)
        {

            UporabnikovPrevoz prevoz = Povprasevanja.getPrevozByID(id);
            return View(prevoz);
        }

        public ActionResult UPrevozi()
        {
            int id = Int32.Parse(Session["id"].ToString());
            List<UporabnikovPrevoz> list = Povprasevanja.vrniVsePrevoze(id,DateTime.Now);
            return View("Prevozi", list);
        }
        public ActionResult posiljanjeSporocila(int posiljatelj, int prejemnik, string text, int id)
        {
            /*Sporocilo s = new Sporocilo(posiljatelj, prejemnik, text);
            Uporabnik u = new Uporabnik();
            u.PosljiSporocilo(s);
            */
            /*string connectionString = " Data Source =.\\SQLEXPRESS;" +
          "AttachDbFilename = " + "C:\\Users\\Dejan Gregorc\\Desktop\\gitfaks\\feridrive\\TestMVC\\WebAppFeriDrive\\App_Data\\FERIDRIVE.mdf" + "; " +
          "Integrated Security = True;" +
          "Connect Timeout = 30;" +
          "User Instance = True";*/
            var conn = new SqlConnection();
            conn.ConnectionString = connectionString;
            conn.Open();

            string idqery = "Select MAX(id) from sporocilo";

            SqlCommand c = new SqlCommand(idqery, conn);
            var reader = c.ExecuteReader();
            int idq = 0;
            while (reader.Read())
            {
                idq = reader.GetInt32(0);
                break;
            }
            idq += 1;
            string query = "insert into sporocilo(id, id_posiljatelj, id_prejemnik, tekst) values(" + idq + "," + posiljatelj + "," + prejemnik + ",'" + text + "')";

            conn.Close();


            conn.ConnectionString = connectionString;
            conn.Open();
            using (var command = new SqlCommand(query, conn))
            {

                command.ExecuteNonQuery();

            }
            conn.Close();

            int id1 = Int32.Parse(Session["id"].ToString());
            //List<UporabnikovPrevoz> list = Povprasevanja.vrniVsePrevoze(id1);
            //return View("Prevozi", list);
            UporabnikovPrevoz prevoz = Povprasevanja.getPrevozByID(id);
            return View("Details", prevoz);
        }
    }
    }

FERIDriveApp/WebAppFeriDrive/Views/Prevoz/AddPrevoz.cshtml
@model UporabnikovPrevoz

@{
    ViewBag.Title = "Dodajanje prevoza";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodajanje prevoza</h2>


<form action="dodajanjePrevoza" method="get">
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-5">
                    <label for="model">Model avta:</label>
                    <input type="text" class="form-control" name="model" required >
                </div>
                <div class="2 col-md-5">
                    <label for="cena">Cena:</label>
                    <input type="text" class="form-control" name="cena" required >
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-5">
                    <label for="krajOdhoda">Kraj Odhoda:</label>
                    <input type="text" class="form-control" name="krajOdhoda" required >
                </div>
                <div class="col-md-5">
                    <label for="krajPrihoda">Kraj Prihoda:</label>
                    <input type="text" class="form-control" name="krajPrihoda" required >
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-5">
                    <label for="datum">Datum:</label>
                    <input type="date" class="form-control" name="datum" required >
                </div>
                <div class="col-md-5">
                    <label for="ura">Ura:</label>
                    <input type="time" class="form-control" name="ura" required >
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-5">
                    <input type="submit" value="Dodaj prevoz" class="btn btn-primary" />
                </div>
            </div>
        </div>

        </div>
</form>


<div>
  
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FERIDriveApp/WebAppFeriDrive/Views/Prevoz/Details.cshtml
@model UporabnikovPrevoz
@{
    ViewBag.Title = "O Prevozu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("button").click(function () {
                $("#kontaktiranje").toggle();
            });
        });
    </script>
</head>
<h2>Details</h2>
<div>
    <h4>Prevoz</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Cena:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cena) €
        </dd>
        <dt>
            Od:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KrajOd.Ime)
        </dd>
        <dt>
            Začetek:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KrajDo.Ime)
        </dd>
        <dt>
            Odhod ob:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt>
            Uporabnik:
        </dt>
        <dd>
            @Html.ActionLink(Model.Uporabnik.uporabniskoIme, "Profil", "Uporabnik", new { username = Model.Uporabnik.uporabniskoIme }, null)
        </dd>
        <dt>
            Telefonska številka:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Uporabnik.Telefonska)
        </dd>
        <dt>
            Telefonska potrjena:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Uporabnik.TelPotrjena)
        </dd>
        <dt>
            Model avta:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModelAvta)
        </dd>
    </dl>
</div>
<div>
    @if (Session["name"] == null)
    {
        <div><p>Za pošiljanje sporočila se prijavite.</p></div>
    }
    else
    {
        <p>Kontaktiranje prevoznika:</p>
        <div id="kontaktiranje">
            <form method="get" action="~/Prevoz/posiljanjeSporocila">
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-5">
                            <input type="hidden" value="@Html.DisplayFor(model=>model.Uporabnik.Id)" name="prejemnik" />
                            <input type="hidden" value="@Session["id"].ToString()" name="posiljatelj" />
                            <input type="text" name="text" />
                            <input type="hidden" name="id" value="@Html.DisplayFor(model=>model.Id)" />
                        </div>
                    </div>
                </div>

                <input type="submit" value="Pošlji sporočilo:" class="btn btn-primary" />
            </form>
        </div>
    }
</div>

<p>
    @Html.ActionLink("Nazaj", "Prevozi", "Prevoz")
</p>

FERIDriveApp/WebAppFeriDrive/Views/Prevoz/Prevozi.cshtml
@model IEnumerable<UporabnikovPrevoz>

@{
    ViewBag.Title = "Prevozi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<h2>Prevozi</h2>
<br />
<form action="iskanjePrevoza" method="get">
    <div class="row">
        <div class="form-group col-sm-3">
            <h4>Kraj odhoda:</h4>
            <input name="krajOdhoda" id="kOdhoda" class="form-control" type="text" placeholder="Maribor"  />
        </div>
        <div class="col-sm-1 text-center">
            <h4 style="color:snow">.</h4>
            <button type="button" id="menjaj"><i class="glyphicon glyphicon-resize-horizontal vcenter"></i></button>

        </div>
        <div class="form-group col-sm-3">
            <h4>Kraj prihoda:</h4>
            <input name="krajPrihoda" id="kPrihoda" class="form-control" type="text" placeholder="Koper"  />
        </div>
        <div class="form-group col-sm-4">
            <div class="form-group">
                <div class="col col-sm-6">
                    <h4>Datum:</h4>
                    <input type="date" class="form-control" name="datum">
                </div>
                <div class="col col-sm-6">
                    <h4>Ura:</h4>
                    <input type="time" class="form-control" name="ura">
                </div>
            </div>
        </div>
        <div class="form-group col-sm-1">
            <h4 style="color:snow">.</h4>
            <button type="submit" value="Išči"> Išči </button>
        </div>

    </div>
</form>
<br />
<table class="table">
    <tr>
        <th>Cena</th>
        <th>Kraj odhoda</th>
        <th>Kraj prihoda</th>
        <th>Datum </th>
        <th>Ura</th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cena)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KrajOd.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KrajDo.Ime)
            </td>
            <td>
                @item.Datum.ToString(string.Format("dd/MM/yyyy"))
            </td>
            <td>
                @item.Datum.TimeOfDay.ToString()
            </td>
            <td>
                @Html.ActionLink("Podrobno", "Details", "Prevoz", new { id = item.Id }, null)

            </td>
        </tr>
    }

</table>

<script>
    $("#menjaj").click(function () {

        var t = $('#kOdhoda').val();
        $('#kOdhoda').val($('#kPrihoda').val());
        $('#kPrihoda').val(t);

    });

</script>